- name: Terminating instances
    ec2:
      instance_ids: "{{ item.id }}"
      region: "{{ region }}"
      state: stopped
      wait: true
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}" 
    loop: "{{ec2.instances}}"       
